
print('#3.8')
respublici = ['Польша', 'Украина', 'Италия', 'Монако', 'Казахстан']
print('отсортированый(список):')
print(sorted(respublici)) 
print('дефолт')
print(respublic)
print('обратный:')
respublici.reverse()
print(respublici) 
print('дефолт')
respublici.reverse()
print(respublici)
print('отсортировано по list.sort ():')
respublici.sort()
print(respublici) 
print('перевернутый и отсортированный:')
respublici.sort(reverse=1)
print(respublici) 
